### ISSUE TITLE
Chrome Error

### ISSUE THREAD

**Issue by rochapablo** [sachinchoolur/angular-flash#17]
I'm using ```"angular-flash-alert": "latest"``` and today with the last release I got this error:

> Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

```
let id = parseInt(attrs.closeFlash, 10);
```

I'm just reporting... I'll use the 1.1.1 version until this get fixed.

**Comment by RoopeHakulinen** [comment]
Hey @rochapablo,

Sorry to hear that. It seems that you are using .js file from wrong directory. What you should use is [_dist/angular-flash.js_](https://github.com/sachinchoolur/angular-flash/blob/master/dist/angular-flash.js) instead of [_src/angular-flash.js_](https://github.com/sachinchoolur/angular-flash/blob/master/src/angular-flash.js). Please make sure you are using the file from correct folder :)

**Comment by rochapablo** [comment]
Oh! I'm sorry.

You're right, I was loading from /src. My bad.

Thank you.
