### ISSUE TITLE
Error when used without stateparams

### ISSUE THREAD

**Issue by irfaan008** [sachinchoolur/angular-flash#31]
I tried to use this way:
`app.controller('MerchantsCtrl', ['$scope', '$resource', '$location', '$routeParams','Flash', 
    function($scope, $resource, $location,Flash){
        Flash.create('success', "Not Working");
        }]);`

But it doesn't work but when I use stateparams, it works:
`app.controller('MerchantsCtrl', ['$scope', '$resource', '$location', '$stateParams', 'Flash', 
    function($scope, $resource, $location,$stateParams,Flash){
        Flash.create('success', "Working");
        }]);`

I am not sure which of my dependency is causing error.

The error I get in first case is :
**Flash.create is not a function**

**Comment by RoopeHakulinen** [comment]
Hey @irfaan008 I may be missing something but for me it seems really clear why the above doesn't work where as the bottom one works. Since you are using the array notation to define your controller, you need to match the dependencies specified within the first N (5 in your case) values of array with the function parameters you use to "name" them. What I mean is that since you have 5 dependencies (_$scope_, _$resource_ etc.), you also need to place them accordingly as the function parameter names. 

In your first example you have _Flash_ in the place of _$stateParams_ and thus the Flash name refers to that instead. This will obviously lead to _Flash.create_ not being defined as _$stateParams_ do not have method _create_. 

So what I'm trying to say here is that the solution you have provided by yourself is the correct one where you map the dependencies appropriately.
