### ISSUE TITLE
Can this be used with AngularJS 4.x

### ISSUE THREAD

**Issue by nwrbs** [sachinchoolur/angular-flash#56]
If so, are there any coding examples for Angular 4.x.  The example give does not seem to fit the normal angular 4 use as far as I can tell.  I am new to Angular, so it is very possible I missed something or don't completely understand angular-flash use.

**Comment by RoopeHakulinen** [comment]
No, it can *not* be used with Angular (2+) because it is totally different framework than AngularJS (AKA Angular 1). Look alternatives in Google with something like ["Angular 2 flash"](https://www.google.com.sg/search?q=angular+2+flash+message&oq=angular+2+flash&aqs=chrome.0.0j69i57j0l2.1807j0j7&sourceid=chrome&ie=UTF-8) to find for example this Angular-compatible module called [_angular2-flash-messages_](https://www.npmjs.com/package/angular2-flash-messages).

**Comment by nwrbs** [comment]
Thanks.  I would appreciate it as I'm sure others would if your documentation (README.md) stated this up front.  I'm new to Angular, and it is hard to tell which products are compatible with which versions of AngularJS.

Thanks again.

**Comment by RoopeHakulinen** [comment]
I'd be happy to merge in a PR for this. :)
